#logger:
#   default: debug

homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  #customize: !include config/customize.yaml
  packages: !include_dir_named packages

  auth_providers:
   - type: legacy_api_password
     api_password: !secret ha_password
     
     
### Listado dispositivos ###
xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_aqara_mac
      key: !secret xiaomi_aqara_key

tuya:
  username: !secret smartlife_user
  password: !secret smartlife_psw
  country_code: 34
  platform: smart_life

custom_updater:
  show_installable: false
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    # Dev build (unstable)
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/next/custom_components.json
    # Released build
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/Gluwc/bar-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/ljmerza/waze-card/master/custom_updater.json
    - https://raw.githubusercontent.com/cbulock/lovelace-battery-entity/master/tracker.json
        
system_health:


# Show links to resources in log and frontend
introduction:


# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/


# Enables configuration UI
config:


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  api_password: !secret ha_password
  base_url: https://!secret url_ddns:8123
  ssl_certificate: /home/homeassistant/.homeassistant/www/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/www/privkey.pem


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true


# Discover some devices automatically
discovery:
  ignore:
    - igd
    
    
# Enables support for tracking state changes over time
history:


# View all events in a logbook
logbook:


# Enables a map showing the location of tracked devices
map:


# Track the sun
sun:


# Text to speech
tts:
  - platform: google
    language: 'es'
    cache: false
    
    
# Cloud
#cloud:
#  alexa:
#   filter:
#     exclude_domains:
#       - automation
#       - camera
#       - device_tracker
#       - group
#       - input_boolean
#       - input_datetime
#       - input_number
#       - input_select
#       - script
       

# Recorder
recorder:
  purge_keep_days: 15
  exclude:
    domains:
      - automation
      - script
      - group
    entities:
# sistema #
      - sun.sun
      - sensor.time
      - sensor.date
      - sensor.date_template
      - sensor.workday_template
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      - sensor.custom_python_script_tracker
# servidor #
      - sensor.current_version
      - sensor.last_boot
      - sensor.server_uptime
      - sensor.uptime_templated
      - input_number.days_cleanbackup_emby
      - input_number.days_cleanbackup_ha
      - script.backup_clean_emby
      - script.backup_clean_ha
      - script.backup_emby
      - script.backup_emby_update_sensors
      - script.backup_ha
      - script.backup_ha_update_sensors
      - script.update_home_assistant
      - sensor.last_backup_emby
      - sensor.last_backup_ha
      - sensor.backup_count_emby
      - sensor.backup_count_ha
      - sensor.backup_size_total_emby
      - sensor.backup_size_total_ha
      - sensor.ssl_certificate_expiry
      - sensor.cpu_speed
# comedor #
      - input_datetime.aa_comedor_off_festivo
      - input_datetime.aa_comedor_off_laborable
      - input_datetime.aa_comedor_on_festivo
      - input_datetime.aa_comedor_on_laborable
      - input_number.aa_comedor_temp_cool_auto
      - input_number.aa_comedor_temp_cool_on
      - input_number.aa_comedor_temp_heat_auto
      - input_number.aa_comedor_temp_heat_on
      - automation.aa_agua_msg
# cocina #      
      - input_datetime.dishwasher_on
# despacho #
      - automation.miboxania_off
      - automation.miboxania_on
      - input_datetime.miboxania_off
      - input_datetime.miboxania_on
# precio luz #
      - sensor.fecha
      - sensor.hora_recogida_de_datos
      - sensor.maximo_diario_eur_kwh
      - sensor.maximo_diario_hora
      - sensor.minimo_diario_eur_kwh
      - sensor.minimo_diario_hora
# trayecto #
      - input_select.origin
      - input_select.destination
      - sensor.orig_address
      - sensor.dest_address
# vacuum #
      - sensor.vacuum_battery_level
      - sensor.vacuum_clean_stop
      - sensor.vacuum_cleaned_area
      - sensor.vacuum_cleaning_count
      - sensor.vacuum_cleaning_time
      - sensor.vacuum_do_not_disturb
      - sensor.vacuum_fan_speed
      - sensor.vacuum_total_cleaned_area
      - sensor.vacuum_total_cleaning_time
      - input_boolean.vacuum_auto_day0
      - input_boolean.vacuum_auto_day1
      - input_boolean.vacuum_auto_day2
      - input_boolean.vacuum_auto_day3
      - input_boolean.vacuum_auto_day4
      - input_boolean.vacuum_auto_day5
      - input_boolean.vacuum_auto_day6
      - group.vacuum_auto_on
# meteo #
      - sensor.wind_dir
      - camera.meteo_fijo
      - camera.meteo_movil
#      - sensor.u_s_air_pollution_level
#      - sensor.u_s_air_quality_index
#      - sensor.u_s_main_pollutant
# bateria sensores #
      - sensor.battery_ania_temperatura
      - sensor.battery_balcon_temperatura
      - sensor.battery_cocina_movimiento
      - sensor.battery_comedor_aa
      - sensor.battery_comedor_movimiento
      - sensor.battery_comedor_temperatura
      - sensor.battery_comedor_ventana_der
      - sensor.battery_comedor_ventana_izq
      - sensor.battery_dormitorio_temperatura
      - sensor.battery_entrada_puerta
      - sensor.battery_entrada_pulsador
      - sensor.battery_llavero_ania
      - sensor.battery_llavero_isset
      - sensor.battery_llavero_jcc

    
### Aspecto ###
#panel_custom: !include config/panel_custom.yaml
panel_iframe: !include config/panel_iframe.yaml

lovelace :
   mode: yaml
   
   
### Subrutinas ###
#shell_command: !include config/shell_command.yaml


### API ###
api:

alexa:
 smart_home:
   filter:
     exclude_domains:
       - automation
       - binary_sensor
       - camera
       - device_tracker
       - group
       - input_boolean
       - input_datetime
       - input_number
       - input_select
       - light
       - media_player
       - script
       - sensor
       - sun
       - switch
       - vacuum
       - weather
       - zone
     include_entities:
       - script.vacuum_on
       - script.vacuum_home
       - sensor.ania_temperatura
       - sensor.balcon_temperatura
       - sensor.bano_temperatura
       - sensor.cocina_temperatura
       - sensor.comedor_temperatura
       - sensor.despacho_temperatura
       - sensor.dormitorio_temperatura
       - sensor.invitados_temperatura
