title: Home-Server

# https://community.home-assistant.io/t/my-lovelace-plugins/70726
resources:
  - url: /local/custom_ui/auto-entities.js
    type: js
  - url: /local/custom_ui/bar-card.js
    type: js
  - url: /local/custom_ui/battery-entity.js?v=0.1
    type: module
  - url: /local/custom_ui/bignumber-card.js
    type: js
  - url: /local/custom_ui/button-card.js
    type: module
  - url: /local/custom_ui/canvas-gauge-card.js
    type: module
  - url: /local/custom_ui/card-modder.js
    type: js
  - url: /local/custom_ui/card-tools.js?track=true  
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js
    type: module
  - url: /local/custom_ui/dual-gauge-card.js
    type: js
  - url: /local/custom_ui/fold-entity-row.js
    type: js
  - url: /local/custom_ui/forked-daapd-card.js
    type: js
  - url: /local/custom_ui/haiku-global-config.js
    type: module
  - url: /local/custom_ui/haiku-room-card.js
    type: module
  - url: /local/custom_ui/layout-card.js
    type: js
  - url: /local/custom_ui/mini-graph-card-bundle.js
    type: module
  - url: /local/custom_ui/mini-media-player-bundle.js
    type: module
  - url: /local/custom_ui/monster-card.js
    type: js
  - url: /local/custom_ui/popup-card.js?track=true
    type: js
  - url: /local/custom_ui/radial-menu.js
    type: module
  - url: /local/custom_ui/secondaryinfo-entity-row.js
    type: module
  - url: /local/custom_ui/simple-thermostat.js
    type: module    
  - url: /local/custom_ui/slider-entity-row.js
    type: js
  - url: /local/custom_ui/state-switch.js
    type: js
  - url: /local/custom_ui/surveillance-card.js
    type: module    
  - url: /local/custom_ui/swipe-card.js
    type: module    
  - url: /local/custom_ui/time-input-row.js
    type: js
  - url: /local/custom_ui/toggle-lock-entity-row.js
    type: js
  - url: /local/custom_ui/vertical-stack-in-card.js
    type: js
  - url: /local/custom_ui/weather-card.js
    type: module 
  - url: /local/custom_ui/waze-card.js?v=2.0.0
    type: js    
  - url: /local/tracker-card.js
    type: js

views:
  - !include lovelace/00_main.yaml
  - !include lovelace/01_vacuum.yaml
  - !include lovelace/01_vacuum_2.yaml
  - !include lovelace/10_casa.yaml
  - !include lovelace/20_servidor.yaml
  - !include lovelace/30_media.yaml
  - !include lovelace/40_meteo.yaml
  - !include lovelace/50_informacion.yaml
  - !include lovelace/99_hidden.yaml
