title: Home-Server

# https://community.home-assistant.io/t/my-lovelace-plugins/70726
resources:
  - url: /local/custom_ui/dual-gauge-card.js
    type: js
  - url: /local/custom_ui/monster-card.js
    type: js
  - url: /local/custom_ui/bignumber-card.js
    type: js
  - url: /local/custom_ui/weather-card.js
    type: module 
  - url: /local/custom_ui/card-tools.js?track=true  
    type: js
  - url: /local/custom_ui/secondaryinfo-entity-row.js
    type: module
  - url: /local/tracker-card.js
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js
    type: module
  - url: /local/custom_ui/card-modder.js
    type: js
  - url: /local/custom_ui/slider-entity-row.js
    type: js
  - url: /local/custom_ui/auto-entities.js
    type: js
  - url: /local/custom_ui/fold-entity-row.js
    type: js
  - url: /local/custom_ui/layout-card.js
    type: js
  - url: /local/custom_ui/popup-card.js?track=true
    type: js
  - url: /local/custom_ui/time-input-row.js
    type: js
  - url: /local/custom_ui/state-switch.js
    type: js
  - url: /local/custom_ui/vertical-stack-in-card.js
    type: js
  - url: /local/custom_ui/canvas-gauge-card.js
    type: module
  - url: /local/custom_ui/button-card.js
    type: module
  - url: /local/custom_ui/haiku-global-config.js
    type: module
  - url: /local/custom_ui/haiku-room-card.js
    type: module
  - url: /local/custom_ui/surveillance-card.js
    type: module    
  - url: /local/custom_ui/simple-thermostat.js
    type: module    
  - url: /local/custom_ui/toggle-lock-entity-row.js
    type: js
  - url: /local/custom_ui/mini-media-player-bundle.js
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js
    type: module
    
views:
  - !include lovelace/00_main.yaml
  - !include lovelace/01_vacuum.yaml
#  - !include lovelace/01_vacuum_a.yaml
  - !include lovelace/10_casa.yaml
  - !include lovelace/20_servidor.yaml
  - !include lovelace/30_media.yaml
  - !include lovelace/40_meteo.yaml
  - !include lovelace/50_informacion.yaml

excluded_entities:
# grupos
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_scripts
  - group.all_switches
  - group.all_vacuum_cleaners
  - group.backup_emby
  - group.backup_ha
  - group.balcon
  - group.batteries
  - group.cocina
  - group.comedor
  - group.despacho
  - group.dormitorio
  - group.entrada
  - group.habitacion_ania
  - group.info
  - group.info_amule
  - group.info_ha
  - group.info_server
  - group.network
  - group.precioluz
  - group.rooms
  - group.router
  - group.system
  - group.device_tracker
  - automation.a_adb_start
  - sensor.date
  - sensor.last_boot
  - sensor.uptime
  - sensor.custom_card_tracker
  - sensor.custom_component_tracker
  - sensor.custom_python_script_tracker
# AA comedor #
  - automation.dash1
  - script.aa_comedor_auto
  - script.aa_comedor_cool
  - script.aa_comedor_heat
  - script.aa_comedor_off
# llaveros #
  - automation.alarma_apagada_jcc
  - automation.alarma_apagada_isset
  - automation.alarma_apagada_ania
  - device_tracker.amazfit_cor
  - device_tracker.mi_band_2_juanrubio
# media player
  - group.info_ffmpeg
  - group.media
  - group.media_player
  - media_player.this_device
# meteo
  - automation.weather_msg_storm
  - group.meteo
  - group.meteo_0
  - group.meteo_1
  - group.weather
  - sensor.dark_sky_icon
  - sensor.dark_sky_wind_bearing
  - sensor.tormenta
  - sun.sun
# robot aspirador #
  - automation.vacuum_msg_charging
  - automation.vacuum_msg_error
  - automation.vacuum_msg_finish
  - automation.vacuum_msg_pause
  - automation.vacuum_msg_return
  - automation.vacuum_msg_start
  - sensor.vacuum_battery_level
  - sensor.vacuum_fan_speed 
  - sensor.vacuum_clean_stop
  - sensor.vacuum_cleaned_area
  - sensor.vacuum_cleaning_count
  - sensor.vacuum_cleaning_time
  - sensor.vacuum_do_not_disturb
  - sensor.vacuum_fan_speed
  - sensor.vacuum_filter_left
  - sensor.vacuum_main_brush_left
  - sensor.vacuum_sensors_clean_left
  - sensor.vacuum_side_brush_left
  - sensor.vacuum_status
  - sensor.vacuum_total_cleaned_area
  - sensor.vacuum_total_cleaning_time
  - vacuum.clin
# server
  - script.backup_ha_update_sensors
  - script.backup_emby_update_sensors
  - script.update_home_assistant
  - switch.servidor_medidor
  - switch.plug_158d000245d060



## SCRIPT TEMPLATE ###
#{%- macro plural(name) -%}
#{%- if name[(name|length|int -1):] == "y" -%}
#{{- name[:-1] -}}ies
#{%- else -%}
#{{- name -}}s
#{%- endif -%}
#{%- endmacro -%}
#title: My Lovely Home Automation
#views:
#- title: Home
#cards:
#{%- set domains = states | map(attribute='domain') |list | unique | list %}
#{%- for item in states['camera'] %}
#- id: {{ item.entity_id.replace('.', '_') }}
#type: picture-entity 
#title: {{ item.name }}
#entity: {{ item.entity_id }}
#camera_image: {{ item.entity_id }}
#show_info: true
#tap_action: dialog
#{% endfor %}
#{%- for item in states['media_player'] %}
#- type: media-control
#entity: {{ item.entity_id }}
#{% endfor %}
#{%- for item in domains if item != "camera" and item != "media_player" %}
#- type: {% if item == "device_tracker" -%}
#entity-filter
#{%- elif item == "camera" -%}
#picture-entity
#{%- else -%}
#entities
#{%- endif %}
#{%- if states[item]|list |length|default(0)|int > 1 %}
#title: {{ plural(item.replace('_', ' ') | title) }}
#{%- else %}
#title: {{ item.replace('_', ' ') | title }}
#{%- endif %}
#show_header_toggle: true
#entities:
#{%- for e in states[item] %}
#- {{ e.entity_id }}
#{%- endfor %}
#{%- if item == "device_tracker" %}
#state_filter:
#- 'home'
#card:
#type: glance
#title: My Device Trackers
#{% endif %}
#{% endfor -%}

