### Panel Alarma ###
  - name: alarm
    sidebar_title: Alarma
    sidebar_icon: mdi:shield-home
    config:
      alarmid: alarm_control_panel.alarma


### Meteo ###
#  - name: meteo
#    sidebar_title: Meteo
#    sidebar_icon: mdi:weather-sunny
#    config:

