## Sensores ##
input_datetime:
  dishwasher_on:
    name: Hora encendido
    has_date: false
    has_time: true


## Scripts ##
script:
  dishwasher_auto:
    alias: Dishwasher timer auto
    sequence:
      - service: automation.turn_on
        data:
          entity_id: automation.dishwasher_on
      - service: input_datetime.set_datetime
        data_template:
          entity_id: input_datetime.dishwasher_on
          time: "{{ (states('sensor.minimo_diario_hora')) }}"
     
 
## Automatizaciones ##
automation:
  - alias: dishwasher_on
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.dishwasher_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: switch.turn_on
      entity_id: switch.cocina_lavavajillas
    - delay: '00:00:10'
    - service: automation.turn_off
      entity_id: automation.dishwasher_on


## Personalizacion ##
homeassistant:
  customize:
    input_datetime.dishwasher_on:
      icon: mdi:clock-outline   
    switch.cocina_lavavajillas:
      icon: mdi:dishwasher
    automation.dishwasher_on:
      friendly_name: Encendido programado
      icon: mdi:calendar-clock
    script.dishwasher_auto:
      friendly_name: Programa automatico


## Grupo ##
group:
  cocina:
    name: Cocina
    control: hidden
    entities:
    - sensor.cocina_iluminacion
    - binary_sensor.cocina_movimiento
    - switch.cocina_lavavajillas
    - automation.dishwasher_on
    - input_datetime.dishwasher_on
    - script.dishwasher_auto
 