## Sensores ##
sensor:
  - platform: template
    sensors:
      windchill_comedor:
        value_template: '{{ ((states.sensor.comedor_temperatura.state|float) + 0.348*((((states.sensor.comedor_humedad.state|float)/100)*6.105)*(2.71828**((17.27*(states.sensor.comedor_temperatura.state|float))/(237.7+(states.sensor.comedor_temperatura.state|float))))) - 4.25) | round(2) }}'
        friendly_name: Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'


## Automatizaciones ##
automation:
  - alias: comedor_quitamiedos
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.comedor_movimiento
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.comedor_iluminacion
          below: '40'
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
    action:
      - service: light.turn_on 
        data:
          entity_id: light.gateway_luz
          color_name: blue
          brightness_pct: 20
      - delay: '00:00:10'
      - service: light.turn_off
        entity_id: light.gateway_luz
        


## Personalizacion ##
homeassistant:
  customize:
    binary_sensor.comedor_ventana_izq:
      device_class: window
    binary_sensor.comedor_ventana_der:
      device_class: window
    sensor.comedor_iluminacion:
      unit_of_measurement: lx
    sensor.comedor_presion:
      unit_of_measurement: mbar
    switch.servidor_medidor:
      hidden: true


## Grupo ##
group:
  comedor:
    name: Comedor
    control: hidden
    entities:
    - sensor.comedor_temperatura
    - sensor.comedor_humedad
    - sensor.comedor_presion
    - sensor.comedor_iluminacion
    - binary_sensor.comedor_movimiento
    - switch.comedor_enchufe
    - switch.servidor_medidor
    - light.gateway_luz
    - binary_sensor.comedor_aire_acondicionado
    - binary_sensor.comedor_ventana_izq
    - binary_sensor.comedor_ventana_der
