## Sensores ##
input_datetime:
  miboxania_on:
    name: Hora encendido
    has_date: false
    has_time: true

  miboxania_off:
    name: Hora apagado
    has_date: false
    has_time: true


## Automatizaciones ##
automation:
  - alias: miboxania_on
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.miboxania_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: switch.turn_on
      entity_id: switch.ania_media

  - alias: miboxania_off
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.miboxania_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    action:
    - service: switch.turn_off
      entity_id: switch.ania_media


## Personalizacion ##
homeassistant:
  customize:
    switch.ania_media:
      icon: mdi:youtube-tv
    automation.miboxania_on:
      friendly_name: Encendido programado
      icon: mdi:calendar-clock
    automation.miboxania_off:
      friendly_name: Apagado programado
      icon: mdi:calendar-clock


## Grupo ##
#group:
#  despacho:
#    name: Despacho
#    control: hidden
#    entities:
#    - switch.ania_media
#    - automation.miboxania_on
#    - input_datetime.miboxania_on
#    - automation.miboxania_off
#    - input_datetime.miboxania_off
#    - media_player.mibox_ania
