## Sensores ##
sensor:
  - platform: template
    sensors:
      windchill_ania:
        value_template: '{{ ((states.sensor.ania_temperatura.state|float) + 0.348*((((states.sensor.ania_humedad.state|float)/100)*6.105)*(2.71828**((17.27*(states.sensor.ania_temperatura.state|float))/(237.7+(states.sensor.ania_temperatura.state|float))))) - 4.25) | round(2) }}'
        friendly_name: Ania - Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'


## Personalización ##
homeassistant:
  customize:
    sensor.ania_presion:
      unit_of_measurement: mbar
