## Sensores ##
sensor:
  - platform: template
    sensors:
      windchill_comedor:
        value_template: '{{ ((states.sensor.comedor_temperatura.state|float) + 0.348*((((states.sensor.comedor_humedad.state|float)/100)*6.105)*(2.71828**((17.27*(states.sensor.comedor_temperatura.state|float))/(237.7+(states.sensor.comedor_temperatura.state|float))))) - 4.25) | round(2) }}'
        friendly_name: Comedor - Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'


## Automatizaciones ##
automation:
  - alias: comedor_luzpaso
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.comedor_movimiento
    condition:
      condition: and
      conditions:
        - condition: time
          after: '23:00:00'
          before: '08:00:00'
        - condition: numeric_state
          entity_id: sensor.comedor_iluminacion
          below: '40'
#        - condition: state
#          entity_id: media_player.samsung_led46_ue46f7000
#          state: 'off'
        - condition: template
          value_template: "{{ states('media_player.samsung_led46_ue46f7000') != 'on' }}"
        - condition: state
          entity_id: binary_sensor.comedor_aire_acondicionado
          state: 'off'
    action:
      - service: light.turn_on 
        data:
          entity_id: light.gateway_luz
          color_name: blue
          brightness_pct: 20
      - delay: '00:00:10'
      - service: light.turn_off
        entity_id: light.gateway_luz
        


## Personalizacion ##
homeassistant:
  customize:
    binary_sensor.comedor_ventana_izq:
      device_class: window
    binary_sensor.comedor_ventana_der:
      device_class: window
    sensor.comedor_iluminacion:
      unit_of_measurement: lx
    sensor.comedor_presion:
      unit_of_measurement: mbar
    switch.servidor_medidor:
      hidden: true
