## Sensores ##
sensor:
  - platform: template
    sensors:
      windchill_invitados:
        value_template: '{{ ((states.sensor.invitados_temperatura.state|float) + 0.348*((((states.sensor.invitados_humedad.state|float)/100)*6.105)*(2.71828**((17.27*(states.sensor.invitados_temperatura.state|float))/(237.7+(states.sensor.invitados_temperatura.state|float))))) - 4.25) | round(2) }}'
        friendly_name: Initados - Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'
