## Informacion ##
sensor:
  - platform: uptime
    unit_of_measurement: minutes

  - platform: template
    sensors:
      uptime_templated:
        entity_id: sensor.uptime
        icon_template: mdi:clock-start
        value_template: >-
          {% set uptime = states.sensor.uptime.state | int %}
          {% set minutes = (uptime % 60) | int %}
          {% set hours = ((uptime % 1440) / 60) | int %}
          {% set days = (uptime / 1440) | int %}
          {{ days }}d {{ ' : ' }} {{ hours }}h {{ ' : ' }} {{ minutes }}m

  - platform: version
    scan_interval: 1200

  - platform: command_line
    name: Last HA Version
    scan_interval: 1200
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
 
 
## Scripts ##
script:
  restart_home_assistant:
    alias: Restart Home Assistant
    sequence:
      - service: homeassistant.restart
        
#  update_home_assistant:
#    alias: Update Home Assistant
#    sequence:
#      - service: shell_command.update_ha
##      - service: homeassistant.restart

 
## Comandos  ##
#shell_command:
#  update_ha: echo {{ !secret sudo_psw_ha }} | sudo -S /home/homeassistant/.homeassistant/scripts/update_ha.sh
#  update_ha: ssh /home/homeassistant/.homeassistant/scripts/update_ha.sh'
#  update_ha: ssh homeassistant@192.168.3.10 sudo bash /home/homeassistant/.homeassistant/scripts/update_ha.sh
#  update_ha: echo "dunkelHA" | sudo -S /home/homeassistant/.homeassistant/scripts/update_ha.sh
#  update_ha: echo {{ !secret sudo_psw_ha }} | sudo -S /home/homeassistant/.homeassistant/scripts/update_ha.sh


## Automatizaciones ##
automation:


## Personalizacion ##
homeassistant:
  customize:
    sensor.uptime:
      hidden: true
    sensor.uptime_templated:
      friendly_name: Tiempo activo
      icon: mdi:clock-start
    sensor.current_version:
      friendly_name: Versión actual
      icon: mdi:home-assistant
    sensor.last_ha_version:
      friendly_name: Última versión
      icon: mdi:home-alert
    script.restart_home_assistant:
      friendly_name: Reiniciar HA
      icon: mdi:restart
    script.update_home_assistant:
      friendly_name: Actualizar HA
      icon: mdi:update
#      icon: mdi:shield-cross-outline
#      icon: mdi:skull-crossbones-outline
    updater.updater:
       hidden: true

 
## Grupo ##
#group:
#  info_HA:
#    name: Home Assistant
#    control: hidden
#    entities:
#    - sensor.uptime_templated
#    - sensor.current_version
#    - sensor.last_ha_version
#    - script.restart_home_assistant
#    - script.update_home_assistant
