## Automatizaciones ##
automation:
  - alias: Alarma apagada - JCC
    trigger:
      - platform: state
        entity_id: binary_sensor.llavero_jcc
    condition:
      - condition: state
        entity_id: 'switch.comedor_enchufe'
        state: 'off'
    action:
    - service: notify.administrador
      data:
        message: "Alarma desactivada por JCC"
    - delay: '00:00:10'

  - alias: Alarma apagada - Isset
    trigger:
      - platform: state
        entity_id: binary_sensor.llavero_isset
    condition:
      - condition: state
        entity_id: 'switch.comedor_enchufe'
        state: 'off'
    action:
      - service: notify.administrador
        data:
          message: "Alarma desactivada por Isset"
      - delay: '00:00:10'

  - alias: Alarma apagada - Ania
    trigger:
      - platform: state
        entity_id: binary_sensor.llavero_ania
    condition:
      - condition: state
        entity_id: 'switch.comedor_enchufe'
        state: 'off'
    action:
      - service: notify.administrador
        data:
          message: "Alarma desactivada por Ania"
      - delay: '00:00:10'


## Personalizacion ##
homeassistant:
  customize:
    binary_sensor.llavero_jcc:
      icon: mdi:account-key 
    binary_sensor.llavero_isset:
      icon: mdi:account-key 
    binary_sensor.llavero_ania:
      icon: mdi:account-key 


## Grupo ##
#group:
#  telegram:
#    name: Telegram
#    entities:
#    - automation.alarma_apagada_jcc
#    - automation.alarma_apagada_isset
#    - automation.alarma_apagada_ania

