## Sensores ##
sensor:
  - platform: co2signal
    token:  !secret co2_token
    country_code: es
    latitude: !secret latitude
    longitude: !secret longitude

  - platform: darksky
    api_key: !secret darksky_api_key
    language: es
#    forecast:
#      - 0
#      - 1
#      - 2
#      - 3
#      - 4
#      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 15
    
  - platform: template
    sensors:
      wind_dir:
        friendly_name: 'Dirección del viento'
        icon_template: mdi:compass
        value_template: >-
          {% set wind_dir = states.sensor.dark_sky_wind_bearing.state %}
          {% if wind_dir | float<=11 %}Norte
          {% elif wind_dir | float>348 %}Norte
          {% elif 11 < (wind_dir|float) <=34 %}NNE
          {% elif 34 < (wind_dir|float) <=56 %}Noreste
          {% elif 56 < (wind_dir|float) <=79 %}}ENE
          {% elif 79 < (wind_dir|float) <=101 %}Este
          {% elif 101 < (wind_dir|float) <=124 %}ESE
          {% elif 124 < (wind_dir|float) <=146 %}Sureste
          {% elif 146 < (wind_dir|float) <=169 %}SSE
          {% elif 169 < (wind_dir|float) <=191 %}Sur
          {% elif 191 < (wind_dir|float) <=214 %}SSO
          {% elif 214 < (wind_dir|float) <=236 %}Suroeste
          {% elif 236 < (wind_dir|float) <=259 %}OSO
          {% elif 259 < (wind_dir|float) <=281 %}Oeste
          {% elif 281 < (wind_dir|float) <=304 %}ONO
          {% elif 304 < (wind_dir|float) <=326 %}Noroeste
          {% elif 326 < (wind_dir|float) <=348 %}NNO
          {%- endif %}

  - platform: template
    sensors:
      storm_dir:
        friendly_name: 'Dirección tormenta más cercana'
        icon_template: mdi:weather-lightning
        value_template: >-
          {% set storm_dir = states.sensor.dark_sky_nearest_storm_bearing.state %}
          {% if storm_dir=="unknown" %}Desconocido
          {% elif storm_dir | float<=11 %}Norte
          {% elif storm_dir | float>348 %}Norte
          {% elif 11 < (storm_dir|float) <=34 %}NNE
          {% elif 34 < (storm_dir|float) <=56 %}Noreste
          {% elif 56 < (storm_dir|float) <=79 %}}ENE
          {% elif 79 < (storm_dir|float) <=101 %}Este
          {% elif 101 < (storm_dir|float) <=124 %}ESE
          {% elif 124 < (storm_dir|float) <=146 %}Sureste
          {% elif 146 < (storm_dir|float) <=169 %}SSE
          {% elif 169 < (storm_dir|float) <=191 %}Sur
          {% elif 191 < (storm_dir|float) <=214 %}SSO
          {% elif 214 < (storm_dir|float) <=236 %}Suroeste
          {% elif 236 < (storm_dir|float) <=259 %}OSO
          {% elif 259 < (storm_dir|float) <=281 %}Oeste
          {% elif 281 < (storm_dir|float) <=304 %}ONO
          {% elif 304 < (storm_dir|float) <=326 %}Noroeste
          {% elif 326 < (storm_dir|float) <=348 %}NNO
          {%- endif %}

  - platform: template
    sensors: 
      tormenta:
        friendly_name: Tormenta
        value_template: >-
          {{ states.sensor.dark_sky_nearest_storm_distance.state|float < 9 and states.sensor.dark_sky_precip_probability.state|float > 80 }}

  - platform: airvisual
    api_key: !secret airvisual_api
    monitored_conditions:
      - us
    show_on_map: true
    scan_interval: 600
    latitude: !secret latitude
    longitude: !secret longitude
    
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

camera: 
  - platform: generic
    still_image_url: https://api.sat24.com/mostrecent/SP/rainTMC
    name: Meteo Fijo
    scan_interval:
      minutes: 5
  - platform: generic
    still_image_url: https://api.sat24.com/animated/SP/rainTMC/1/Central%20European%20Standard%20Time/
    name: Meteo Movil
    scan_interval:
      minutes: 5


## Automatizaciones ##
automation:
  - alias: weather_msg_storm
    trigger:
    - entity_id: binary_sensor.tormenta
      from: 'off'
      platform: state
      to: 'on'
    action:
    - data_template:
        message: La probabilidad de lluvia es de {{states.sensor.dark_sky_precip_probability.state}}%.
          La tormenta esta a {{states.sensor.dark_sky_nearest_storm_distance.state}} km de distancia.
        title: ATENCION TORMENTA
      service: notify.domotica_en_casa
    - data:
        caption: Radar lluvia
        url: https://api.sat24.com/mostrecent/SP/rainTMC
      service: telegram_bot.send_photo
    - data:
        caption: Radar lluvia historico
        url: https://api.sat24.com/animated/SP/rainTMC/1/W_dot_%20Europe%20Standard%20Time/
      service: telegram_bot.send_video


## Personalizacion ##
homeassistant:
  customize:
    sensor.dark_sky_summary:
      friendly_name: Resumen
#    sensor.dark_sky_nearest_storm_bearing:
#      hidden: true
    sensor.dark_sky_nearest_storm_distance:
      friendly_name: "Distancia tormenta más cercana"
    sensor.dark_sky_humidity:
      friendly_name: Humedad
    sensor.dark_sky_temperature:
      friendly_name: Temperatura
    sensor.dark_sky_apparent_temperature:
      friendly_name: Sensación térmica
    sensor.dark_sky_wind_speed:
      friendly_name: Velocidad del viento
    sensor.dark_sky_wind_bearing:
      hidden: true
    sensor.dark_sky_precip:
      friendly_name: Precipitación
    sensor.dark_sky_precip_probability:
      friendly_name: Probabilidad lluvia
    sensor.dark_sky_precip_intensity:
      friendly_name: Intensidad lluvia
    sensor.dark_sky_uv_index:
      friendly_name: Indice UV
    sensor.dark_sky_daily_summary:
      friendly_name: Resumen diario
    sensor.dark_sky_pressure:
      friendly_name: Presion
    sensor.dark_sky_visibility:
      friendly_name: Visibilidad
    automation.weather_msg_storm:
      friendly_name: Tormenta cercana
      
 
## Grupo ##
#group:
#  meteo:
#    control: hidden
#    entities:
#    - sensor.dark_sky_summary
#    - sensor.dark_sky_nearest_storm_distance
#    - sensor.dark_sky_nearest_storm_bearing
#    - sensor.storm_dir
#    - sensor.dark_sky_humidity
#    - sensor.dark_sky_temperature
#    - sensor.dark_sky_apparent_temperature
#    - sensor.dark_sky_wind_speed
#    - sensor.dark_sky_wind_bearing
#    - sensor.wind_dir
#    - sensor.dark_sky_precip
#    - sensor.dark_sky_precip_probability
#    - sensor.dark_sky_precip_intensity
#    - sensor.dark_sky_uv_index
#    - sensor.dark_sky_daily_summary
#    - sensor.dark_sky_pressure
#    - sensor.dark_sky_visibility
    
