## Informacion HA ##
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
      - ping
      - download
      - upload
 
      
## Personalizacion ##
homeassistant:
  customize:
    sensor.uptime:
      hidden: true

 
## Grupo ##
group:
  network:
    name: Network
    control: hidden
    entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

