## Sensores ##
sensor:
  - platform: scrape
    resource: http://www.tarifadeluz.com
    name: Fecha
    scan_interval: 99999
    select: 'div:nth-of-type(9)'
    value_template: >-
      {% for i in range(2, 8) %}
        {{ value.split()[i] }}
      {% endfor%}

  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: Hora Recogida de Datos
    scan_interval: 300
    select: 'div:nth-of-type(6)'
    value_template: '{{ value.split()[7] }}'

  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: Actual (€/KWH)
    scan_interval: 300
    select: 'font[color^="white"] > b'
    value_template: '{{ value.split(" ")[0] }}'
    unit_of_measurement: '€/kWh'
      
  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: "Minimo Diario (Hora)"
    scan_interval: 99999
    select: 'div:nth-of-type(10)'
    value_template: '{{ value.split()[4] }}'

  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: "Minimo Diario (€/KWH)"
    scan_interval: 99999
    select: 'div:nth-of-type(10)'
    value_template: '{{ value.split()[0] }}'
    unit_of_measurement: '€/kWh'
  
  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: "Maximo Diario (Hora)"
    scan_interval: 99999
    select: 'div:nth-of-type(13)'
    value_template: '{{ value.split()[4] }}'

  - platform: scrape
    resource: http://www.tarifadeluz.com/
    name: "Maximo Diario (€/KWH)"
    scan_interval: 99999
    select: 'div:nth-of-type(13)'
    value_template: '{{ value.split()[0] }}'
    unit_of_measurement: '€/kWh'

    
## Automatizaciones ##
automation:
  - alias: Scrape Tarifa Luz
    initial_state: true
    trigger:
      platform: time
      at: 00:01:00
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.fecha
      - service: homeassistant.update_entity
        entity_id: sensor.minimo_diario_hora
      - service: homeassistant.update_entity
        entity_id: sensor.minimo_diario_eur_kwh
      - service: homeassistant.update_entity
        entity_id: sensor.maximo_diario_hora
      - service: homeassistant.update_entity
        entity_id: sensor.maximo_diario_eur_kwh


## Personalizacion ##
homeassistant:
  customize:
    sensor.fecha:
      icon: mdi:calendar-range
    sensor.hora_recogida_de_datos:
      icon: mdi:clock-outline
    sensor.actual_eur_kwh:
      icon: mdi:currency-eur
    sensor.minimo_diario_hora:
      icon: mdi:thumb-up
    sensor.minimo_diario_eur_kwh:
      icon: mdi:currency-eur
    sensor.maximo_diario_hora:
      icon: mdi:thumb-down
    sensor.maximo_diario_eur_kwh:
      icon: mdi:currency-eur


## Grupo ##
group:
  precioluz:
    name: Precio Luz
    control: hidden
    entities:
    - sensor.fecha
    - sensor.hora_recogida_de_datos
    - sensor.actual_eur_kwh
    - sensor.minimo_diario_hora
    - sensor.minimo_diario_eur_kwh
    - sensor.maximo_diario_hora
    - sensor.maximo_diario_eur_kwh
