## Informacion ##
sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: template
    sensors:
      date_template:
        entity_id: sensor.date
        value_template: >
          {% set weekdays = ["Lunes ", "Martes ", "Miercoles ", "Jueves ", "Viernes ", "Sabado ", "Domingo "]  %}
          {% set weekday = weekdays[now().strftime('%w') | int -1] %}
          {{ weekday }}, {{ as_timestamp(now()) | timestamp_custom("%d/%m/%Y", True) }}
          
binary_sensor:
  - platform: workday
    country: ES
    province: CAT


## Personalizacion ##
homeassistant:
  customize:
    sensor.time:
      friendly_name: Hora
    sensor.date:
      hidden: true
    sensor.date_template:
      friendly_name: Fecha
      icon: mdi:calendar-range
    binary_sensor.workday_sensor:
      friendly_name_template: >
        {% if is_state('binary_sensor.workday_sensor', 'on') %}
          Laborable
        {% else %}
          Festivo
        {% endif %}
