## Informacion ##
sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: template
    sensors:
      date_template:
        entity_id: sensor.date
        value_template: >
          {% set weekdays = ["Lunes ", "Martes ", "Miercoles ", "Jueves ", "Viernes ", "Sabado ", "Domingo "]  %}
          {% set weekday = weekdays[now().strftime('%w') | int -1] %}
          {{ weekday }}, {{ as_timestamp(now()) | timestamp_custom("%d/%m/%Y", True) }}
          
  - platform: template
    sensors:
      workday_template:
#        value_template: '{{states.binary_sensor.workday_sensor.state}}'
        value_template: >-
          {% if is_state('binary_sensor.workday_sensor', 'on') %}
            Si
          {% else %}
            No
          {% endif %}
        friendly_name: Laborable
        icon_template: >
          {% if is_state('binary_sensor.workday_sensor' ,'on') %}
            mdi:briefcase
          {% else %}
            mdi:beach
          {% endif %}

binary_sensor:
  - platform: workday
    country: ES
    province: CAT


## Personalizacion ##
homeassistant:
  customize:
    sensor.time:
      friendly_name: Hora
    sensor.date:
      hidden: true
    sensor.date_template:
      friendly_name: Fecha
      icon: mdi:calendar-range
    binary_sensor.workday_sensor:
      friendly_name: Laborable
      icon: mdi:briefcase
