## Sensores ##
device_tracker:
  - platform: bluetooth_le_tracker
    track_new_devices: false
    interval_seconds: 60
    consider_home: 240
    blacklist_names:
      - 'dtvbluetooth'
      - 'tv_samsung_led46'
      - 'ulefone_s7'
      - 'mibox_ania'
      - 'ble_3c_bd_xx_xx_xx_xx'
      - 'ble_68_a8_xx_xx_xx_xx'
      - 'ble_58_d8_xx_xx_xx_xx'
      - 'mibcs'
#    hci_device: 'hci0'
#    hide_unnamed: true

#  - platform: bluetooth_le_tracker
#    interval_seconds: 60
#    new_device_defaults:
#      track_new_devices: true

#  - platform: bluetooth_tracker
#    interval_seconds: 60
#    new_device_defaults:
#      track_new_devices: true
      
input_select:
  origin:
    name: origen
    icon: mdi:arrow-expand-right
    options:
      - Casa
      - Trabajo
      - Colegio
  destination:
    name: destino
    icon: mdi:arrow-collapse-right
    options:
      - Casa
      - Trabajo
      - Colegio
      
sensor:
  - platform: template
    sensors:
       orig_address:
         value_template: >-
            {%- if is_state("input_select.origin", "Casa")  -%}
              Calle TU CASA, nn, CP Barcelona, Spain
            {%- elif is_state("input_select.origin", "Trabajo")  -%}
              Plaza TRABAJO, n, CP Barcelona, Spain
            {%- elif is_state("input_select.origin", "Colegio")  -%}
              Rambla COLEGIO, nn, CP Barcelona, Spain
            {%- else -%}
              Madrid, Spain
            {%- endif %}
  - platform: template
    sensors:
       dest_address:
         value_template: >-
            {%- if is_state("input_select.destination", "Casa")  -%}
              Calle TU CASA, nn, CP Barcelona, Spain
            {%- elif is_state("input_select.destination", "Trabajo")  -%}
              Plaza TRABAJO, n, CP Barcelona, Spain
            {%- elif is_state("input_select.destination", "Colegio")  -%}
              Rambla COLEGIO, nn, CP Barcelona, Spain
            {%- else -%}
              Sevilla, Spain
            {%- endif %}

  - platform: waze_travel_time
    name: "Trayecto"
    origin: sensor.orig_address
    destination: sensor.dest_address
    region: 'EU'
