# https://community.home-assistant.io/t/xiaomi-vacuum-cleaner-card/64456

## Dispositivo ##
vacuum:
  - platform: xiaomi_miio
    host: 192.168.3.203
    token: !secret roborock_token
    name: Clin


## Informacion ##
sensor:
  - platform: template
    sensors:
      vacuum_status:
        value_template: 'Estado: {{states.vacuum.clin.state}}'
        entity_id: vacuum.clin
        friendly_name: Estado de la aspiradora
        icon_template: mdi:information-variant

  - platform: template
    sensors:
      vacuum_battery_level:
        value_template: 'Batería: {{ states.vacuum.clin.attributes.battery_level }}'
        entity_id: vacuum.clin
        unit_of_measurement: '%'
        friendly_name: Batería restante
        icon_template: mdi:battery

  - platform: template
    sensors:
      vacuum_cleaning_time:
        value_template: 'Tiempo Limpieza: {{ states.vacuum.clin.attributes.cleaning_time }}'
        entity_id: vacuum.clin
        unit_of_measurement: 'minutos'
        friendly_name: Tiempo de limpieza
        icon_template: mdi:timer

  - platform: template
    sensors:
      vacuum_cleaned_area:
        value_template: 'Área Limpiada: {{ states.vacuum.clin.attributes.cleaned_area }}'
        entity_id: vacuum.clin
        unit_of_measurement: 'm²'
        friendly_name: Area limpiada
        icon_template: mdi:vector-square 

  - platform: template
    sensors:
      vacuum_do_not_disturb:
        value_template: '{{ states.vacuum.clin.attributes.do_not_disturb }}'
        entity_id: vacuum.clin
        friendly_name: No molestar
        icon_template: mdi:do-not-disturb

  - platform: template
    sensors:
      vacuum_main_brush_left:
        value_template: 'Cepillo Principal: {{ (states.vacuum.clin.attributes.main_brush_left | round(0) |  int * 100/300) | round(0) }}'
        entity_id: vacuum.clin
        unit_of_measurement: '%'
        friendly_name: Estado del cepillo principal
        icon_template: mdi:broom 

  - platform: template
    sensors:
      vacuum_side_brush_left:
        value_template: 'Cepillo Lateral: {{ (states.vacuum.clin.attributes.side_brush_left | round(0) |  int * 100/200) | round(0) }}'
        entity_id: vacuum.clin
        unit_of_measurement: '%'
        friendly_name: Estado del cepillo lateral
        icon_template: mdi:brush  

  - platform: template
    sensors:
      vacuum_filter_left:
        value_template: 'Estado Filtro: {{ (states.vacuum.clin.attributes.filter_left | round(0) |  int * 100/150) | round(0) }}'
        entity_id: vacuum.clin
        friendly_name: Estado del filtro
        unit_of_measurement: '%'
        icon_template: mdi:filter-variant

  - platform: template
    sensors:
      vacuum_sensors_clean_left:
        value_template: 'Limpieza sensores: {{ (states.vacuum.clin.attributes.sensor_dirty_left | round(0) |  int * 100 / 30) | round(0) }}' 
        friendly_name: Limpieza de los sensores
        unit_of_measurement: '%'
        icon_template: mdi:notification-clear-all      

  - platform: template
    sensors:
      vacuum_cleaning_count:
        value_template: 'Ciclos Limpieza: {{ states.vacuum.clin.attributes.cleaning_count}}'
        entity_id: vacuum.clin
        friendly_name: Número de ciclos de limpieza totales
        icon_template: mdi:counter

  - platform: template
    sensors:
      vacuum_total_cleaned_area:
        value_template: '{{ states.vacuum.clin.attributes.total_cleaned_area}}'
        entity_id: vacuum.clin
        unit_of_measurement: 'm²'
        friendly_name: Área total limpiada
        icon_template: mdi:shape-square-plus

  - platform: template
    sensors:
      vacuum_total_cleaning_time:
        value_template: '{{ states.vacuum.clin.attributes.total_cleaning_time }}'
        entity_id: vacuum.clin
        unit_of_measurement: 'minutos'
        friendly_name: Tiempo total de limpieza
        icon_template: mdi:calendar-clock

  - platform: template
    sensors:
      vacuum_fan_speed:
        friendly_name: Velocidad Aspiración
        entity_id: vacuum.clin
        value_template: 'Modo Aspiración: {{ states.vacuum.clin.attributes.fan_speed }}'
        icon_template: 'mdi:speedometer'      

  - platform: template
    sensors:
      vacuum_clean_stop:
        value_template: 'Última Limpieza: {{ states.vacuum.clin.attributes.clean_stop }}'
        entity_id: vacuum.clin
        friendly_name: Fecha última limpieza
        icon_template: mdi:information-variant

# https://community.home-assistant.io/t/templates-extracting-a-list-array-element-from-a-json-output/72634
# https://github.com/custom-cards/button-card/tree/master/examples
binary_sensor:
  - platform: template
    sensors:
      vacuum_auto_day1:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day2:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day3:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day4:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day5:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day6:
        entity_id: vacuum.clin
        value_template: 0
      vacuum_auto_day7:
        entity_id: vacuum.clin
        value_template: 0

input_datetime:
  vacuum_auto_hour:
    name: Hora encendido
    has_date: false
    has_time: true


## Automatizaciones ##
automation: 
  - alias: vacuum_msg_start
    trigger:
    - entity_id: vacuum.clin
      platform: state
      to: 'cleaning'
    action:
    - service: notify.domotica_en_casa
      data:
        message: 'Comenzando a Limpiar'
      
  - alias: vacuum_msg_pause
    trigger:
    - entity_id: vacuum.clin
      platform: state
      to: 'paused'
    action:
    - service: notify.domotica_en_casa
      data:
        message: 'Aspiradora con problemas, Error: {{ states.sensor.vacuum_status.state }}.' 

  - alias: vacuum_msg_finish
    trigger:
    - entity_id: vacuum.clin
      platform: state
      from: 'cleaning'
      to: 'idle'
    action:
    - service: notify.domotica_en_casa
      data:
        message: 'Limpieza Acabada'           
      
  - alias: vacuum_msg_return
    trigger:
    - entity_id: vacuum.clin
      platform: state
      to: 'returning'
    action:
    - service: notify.domotica_en_casa
      data:
        message: 'Aspiradora de vuelta a la base, {{ states.vacuum.clin.attributes.cleaned_area }} m² fueron aspirados en {{ states.vacuum.clin.attributes.cleaning_time }} minutos.'
      
  - alias: vacuum_msg_charging
    trigger:
    - entity_id: vacuum.clin
      platform: state
      to: 'docked'
    action:
    - service: notify.domotica_en_casa
      data:
        message: 'Cargando clin, {{ states.vacuum.clin.attributes.cleaned_area }} m² fueron aspirados en {{ states.vacuum.clin.attributes.cleaning_time }} minutos.'   
      
################### esto esta en pruebas es para cuando falle diga el error y lo envie,pero no esta aun ########################
  - alias: vacuum_msg_error
    trigger:
      - platform: state
        entity_id: vacuum.clin
        to: 'error'
  #    - platform: state
  #      entity_id: sensor.vacuum_status
  #      to: 'idle'
      - platform: state
        entity_id: vacuum.clin
        to: 'charger disconnected'
    action:
      - service: notify.domotica_en_casa
        data:
          message: 'Aspiradora con problemas, Error: {{ states.sensor.vacuum_status.state }}.'      

  - alias: vacuum_auto_on
    trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.vacuum_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      condition: time
      weekday:
#      {% if is_state('binary_sensor.vacuum_auto_day.day[0]','off') %}
        - mon
 #     {% endif %}     
    action:
    - service: vacuum.start
      data:
        entity_id: vacuum.clin

#        tue
#        wed
#        thu
#        fri
#        sat
#        sun

      
## Grupo ##
group:
  aspiradoracasa:
    name: Aspiradora
    view: yes
    icon: mdi:robot-vacuum-variant
    entities:
      - group.aspiradora

  vacuum_auto_on:
    name: Horarios programados
    icon: mdi:calendar-clock
    entities:
    - input_datetime.vacuum_auto_hour

  aspiradora:
    name: Aspiradora
    view: no
    entities:
      - vacuum.clin
      - sensor.vacuum_do_not_disturb
      - sensor.vacuum_status
      - sensor.vacuum_cleaned_area
      - sensor.vacuum_battery_level   
      - sensor.vacuum_filter_left
      - sensor.vacuum_main_brush_left
      - sensor.vacuum_sensors_clean_left
      - sensor.vacuum_side_brush_left  
      - sensor.vacuum_cleaning_count
      - sensor.vacuum_total_cleaned_area
      - sensor.vacuum_cleaning_time
      - sensor.vacuum_total_cleaning_time
      

## Personalizacion ##
homeassistant:
  customize:
    automation.vacuum_msg_start:
      friendly_name: Empezando a limpiar
    automation.vacuum_msg_pause:
      friendly_name: Limpieza en Pausa
    automation.vacuum_msg_finish:
      friendly_name: Limpieza Acabada
    automation.vacuum_msg_return:
      friendly_name: Regresar a Base
    automation.vacuum_msg_error:
      friendly_name: Error
    automation.vacuum_auto_on:
      friendly_name: Limpieza programada
    group.vacuum_auto_on:
      friendly_name: Programado          
